drivesafe/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "drivesafe"
urlpatterns = [
    path("", views.home, name="index"),
    path('login_view/', views.login_view, name='login'),
    path('accounts/', include('allauth.urls')),
    path('login_redirect/', views.login_redirect, name='login_redirect'),
    path('regular_user_home/', views.regular_user, name='regular_user_home'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('user_report/', views.report, name='report'),
    path('form_submitted/', views.form_submitted, name='form_submitted'),
    path('submissions/', views.view_submissions, name='submissions'),
    path('user_submissions/', views.view_user_submissions, name='user_submissions'),
    path('anonymous_report/', views.anonymous_report, name='anonymous_report'),
    path('update_status/<int:submission_id>/', views.update_status, name='update_status'),
    path('update_response/<int:submission_id>/', views.update_response, name='update_response'),
    path('common_words/', views.common_words, name='common_words'),
    path('submission/<int:submission_id>/delete/', views.delete_submission, name='delete_submission'),
    path('update_status_and_response/<int:submission_id>/', views.update_status_and_response, name='update_status_and_response'),
    path('anon_form_submitted/', views.anon_form_submitted, name='anon_form_submitted')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from drivesafe import views

urlpatterns = [
    path('', views.home, name='home'),
    path('drivesafe/', include('drivesafe.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

drivesafe/models.py
from django.db import models
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone





def validate_pdf_file(value):
    if not value.name.lower().endswith('.pdf'):
        raise ValidationError('Only PDF files are allowed.')

def validate_jpg_file(value):
    if not value.name.lower().endswith('.jpg'):
        raise ValidationError('Only JPG files are allowed.')

def validate_txt_file(value):
    if not value.name.lower().endswith('.txt'):
        raise ValidationError('Only TXT files are allowed.')

class UploadedFiles(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pdf_file = models.FileField(upload_to='pdfs/', validators=[FileExtensionValidator(['pdf']), validate_pdf_file], blank=True, null=True)
    jpg_file = models.FileField(upload_to='jpgs/', validators=[FileExtensionValidator(['jpg']), validate_jpg_file], blank=True, null=True)
    txt_file = models.FileField(upload_to='txts/', validators=[FileExtensionValidator(['txt']), validate_txt_file], blank=True, null=True)
    last_updated = models.DateTimeField(default=timezone.now)
    update_seen = models.BooleanField(default=True)

    LOCATION_CHOICES = [
        ('Central Grounds', 'Central Grounds'),
        ('North Grounds', 'North Grounds'),
        ('The Corner', 'The Corner'),
        ('Jefferson Park Avenue', 'Jefferson Park Avenue'),
        ('Emmet Street', 'Emmet Street'),
    ]

    location = models.CharField(max_length=50, choices=LOCATION_CHOICES, default='Central Grounds', blank=True)
    car_color = models.CharField(max_length=100, default= '', blank=True)
    car_model = models.CharField(max_length=100, default= '', blank=True)
    car_identifying_features = models.CharField(max_length=100, default= '', blank=True)
    driver_details = models.CharField(max_length=300, default= '', blank=True)
    additional_information = models.CharField(max_length=300, default= '', blank=True)
    STATUS_CHOICES = [
        ('New', 'New'),
        ('In Progress', 'In Progress'),
        ('Completed', 'Completed'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='New')
    admin_response = models.CharField(max_length=400, null=True, default='')

    def delete(self, *args, **kwargs):
        # Delete all associated files
        for field in [self.pdf_file, self.jpg_file, self.txt_file]:
            try:
                field.delete(save=False)
            except ValueError:
                pass  # Handle the case where the file doesn't exist

        super().delete(*args, **kwargs)



class ReportingForm(ModelForm):
    class Meta:
        model = UploadedFiles
        fields = ['pdf_file', 'jpg_file', 'txt_file', 'location', 'car_color', 'car_model', 'car_identifying_features', 'driver_details', 'additional_information']
       # fields = ['pdf_file', 'jpg_file', 'location', 'car_color', 'car_model', 'car_identifying_features', 'driver_details', 'additional_information']
        labels = {
            'pdf_file': 'PDF File',
            'jpg_file': 'JPG File',
            'txt_file': 'TXT File',
            'location': 'Location',
            'car_color': 'Car Color',
            'car_model': 'Car Model',
            'car_identifying_features': 'Car Identifying Features',
            'driver_details': 'Driver Details',
            'additional_information': 'Additional Information',
        }


class Submission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # Your existing file fields and other fields

    STATUS_CHOICES = [
        ('New', 'New'),
        ('In Progress', 'In Progress'),
        ('Completed', 'Completed'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='New')

drivesafe/forms.py
from django import forms
class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

drivesafe/views.py
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponseNotAllowed, HttpResponseForbidden
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.shortcuts import redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from .models import ReportingForm, UploadedFiles, Submission
from django.conf import settings
from collections import Counter
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
from .forms import LoginForm
nltk.download('punkt')
nltk.download('stopwords')

def home(request):
    HttpResponse("Hello, world! This is the home page.")
    login_url = reverse_lazy('account_login')
    return render(request, 'drivesafe/index.html', {'login_url': login_url})

def submissions_list(request):
    submissions = Submission.objects.all()
    return render(request, 'submissions.html', {'submissions': submissions})

@staff_member_required
def update_status(request, submission_id):
    if request.method == 'POST':
        submission = get_object_or_404(UploadedFiles, pk=submission_id)
        #submission = UploadedFiles.objects.get(pk=submission_id)
        new_status = request.POST.get('status')
        submission.status = new_status
        submission.save()
        messages.success(request, f"Status updated successfully for {submission.user.username}.")
        return redirect('drivesafe:submissions')
    else:
        return render(request, 'error_page.html', {'error_message': 'Invalid request method'})


@staff_member_required
def update_response(request, submission_id):
    if request.method == 'POST':
        submission = get_object_or_404(UploadedFiles, pk=submission_id)
        new_response = request.POST.get('admin_response')  # Get the new response from the form data
        submission.admin_response = new_response  # Update the admin_response field
        submission.last_updated = timezone.now()
        submission.update_seen = False
        submission.save()
        messages.error(request, 'The response has been added')
        messages.success(request, f"Response updated successfully for {submission.user.username}.")
        return redirect('drivesafe:submissions')  # Redirect to the submissions list page
    else:
        return render(request, 'error_page.html', {'error_message': 'Invalid request method'})


def index(request):
    if request.method == 'GET':
        return render(request, 'drivesafe/index.html')
    else:
        return HttpResponseNotAllowed(['GET'])


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                #messages.success(request, 'You have successfully logged in.')
                # Redirect to a success page or wherever you want
                if request.user.is_staff and not request.user.is_superuser:
                    return redirect('drivesafe:admin_home')
                else:
                    return redirect('drivesafe:regular_user_home')
            else:
                messages.error(request, 'Invalid email or password.')
                # Redirect back to the login page with an error message
                return render(request, 'drivesafe/index.html', {'form': form})
    else:
        form = LoginForm()
        #messages.error(request, 'Invalid email or password.')
    return render(request, 'drivesafe/index.html', {'form': form})

def login_redirect(request):
    #need to work on logic for site vs regular
    if request.user.is_authenticated:
        #return render(request, 'drivesafe/regular_user_home.html')
        if request.user.is_staff and not request.user.is_superuser:
            return redirect('drivesafe:admin_home')
        else:
            return redirect('drivesafe:regular_user_home')
    else:
        return redirect('account_login') #redirect to login page if user is not authenticated

@login_required
def regular_user(request):
    context = {
        'username': request.user.username,
        'full_name': request.user.get_full_name()
    }
    return render(request, 'drivesafe/regular_user_home.html', context)


@staff_member_required
def admin_home(request):
    context = {
        'username': request.user.username,
        'full_name': request.user.get_full_name()
    }
    return render(request, 'drivesafe/site_admin_home.html', context)
#keiufog


def report(request):
    context = {
        'username': request.user.username
    }
    if request.method == 'POST':
        form = ReportingForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = form.save(commit=False)
            uploaded_file.user = request.user
            uploaded_file.save()
            return redirect('drivesafe:form_submitted')  # Redirects to where we want to go when submitted
    else:
        form = ReportingForm()
    return render(request, 'drivesafe/reporting.html', {'form': form}) #redirects to where we want to go if submission is bad,
                                                    # so back to user page or back to the form page if it is different
def form_submitted(request):
    return render(request, 'drivesafe/form_submitted.html')

def anon_form_submitted(request):
    return render(request, 'drivesafe/anon_form_submitted.html')
@login_required
def view_submissions(request):
    if not (request.user.is_staff and not request.user.is_superuser):
        return HttpResponseForbidden("You do not have access to this page.")
    submissions = UploadedFiles.objects.all()
    for submission in submissions:
        if submission.status == 'New':
            submission.status = 'In Progress'
            submission.save()
    return render(request, 'drivesafe/submissions.html', {'submissions': submissions})

def view_user_submissions(request):
    user_submissions = UploadedFiles.objects.filter(user=request.user)
    new_updates = user_submissions.filter(update_seen=False)

    context = {
        'user_submissions': user_submissions,
        'new_updates': new_updates.exists(),
    }

    response = render(request, 'drivesafe/view_user_submissions.html', context)
    new_updates.update(update_seen=True)
    return response

def delete_submission(request, submission_id):
    submission = get_object_or_404(UploadedFiles, pk=submission_id)
    if submission.user == request.user:
        submission.delete()
        messages.success(request, "Submission has been successfully deleted")
    return redirect('drivesafe:user_submissions')

def anonymous_report(request):
    anonymous_user = User.objects.filter(username='anonymous').first()
    if request.method == 'POST':
        form = ReportingForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = form.save(commit=False)
            uploaded_file.user = anonymous_user  # Set user to the anonymous user
            uploaded_file.save()
            return redirect('drivesafe:anon_form_submitted')  # Redirect to a submission confirmation page
    else:
        form = ReportingForm()
    return render(request, 'drivesafe/reporting.html', {'form': form})
def common_words(request):
    submissions = UploadedFiles.objects.all()

    all_text = []
    for submission in submissions:
        all_text.append(submission.car_color)
        all_text.append(submission.car_model)
        all_text.append(submission.car_identifying_features)
        all_text.append(submission.driver_details)
        all_text.append(submission.additional_information)

    stop_words = set(stopwords.words('english'))
    words = word_tokenize(' '.join(all_text))
    words = [word.lower() for word in words if word.isalpha() and word.lower() not in stop_words]

    common_words = Counter(words).most_common(10)

    context = {
        'username': request.user.username,
        'full_name': request.user.get_full_name(),
        'common_words': common_words
    }
    return render(request, 'drivesafe/common_words.html', context)


def submissions_categories(request):
    in_progress_submissions = Submission.objects.filter(status='In Progress')
    completed_submissions = Submission.objects.filter(status='Completed')
    return render(request, 'submissions.html', {'in_progress_submissions': in_progress_submissions, 'completed_submissions': completed_submissions})
@staff_member_required
def update_status_and_response(request, submission_id):
    if request.method == 'POST':
        submission = get_object_or_404(UploadedFiles, pk=submission_id)
        new_status = request.POST.get('status')
        new_response = request.POST.get('admin_response')

        if request.POST.get('action') == 'update_both':
            submission.status = new_status
            submission.admin_response = new_response
            submission.update_seen = False
            submission.save()
            messages.success(request, f"Status and response updated successfully for {submission.user.username}.")
        else:
            if new_status:
                submission.status = new_status
                submission.update_seen = False
                submission.save()
                messages.success(request, f"Status updated successfully for {submission.user.username}.")
            if new_response:
                submission.admin_response = new_response
                submission.update_seen = False
                submission.save()

drivesafe/templates/drivesafe/anon_form_submitted.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block content %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Report Submitted</title>
  {% bootstrap_css %}
</head>
<body>
  <div class="container">
    <div class="row justify-content-center mt-5">
      <div class="col-md-8 text-center">
        <div class="alert alert-success" role="alert">
          <h2 class="display-6">Your report has been successfully submitted!</h2>
        </div>
        <a href="{% url 'drivesafe:index' %}" class="btn btn-primary btn-lg mt-3">Go to Home Page</a>
      </div>
    </div>
  </div>

  {% bootstrap_javascript %}
</body>
</html>
{% endblock %}

drivesafe/templates/drivesafe/common_words.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Frequent Words</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    <style>
        body {
            background-color: #f8f9fa;
        }
        .word-list {
            list-style-type: none;
            padding: 0;
        }
        .word-list li {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
            margin-bottom: 5px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .word-list li:nth-child(odd) {
            background-color: #f0f0f0;
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Frequent Words</h1>
        <ul class="word-list">
            {% for word, count in common_words %}
                {% if count >= 3 %}
                    <li>
                        <span>{{ word }}</span>
                        <span>{{ count }}</span>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
        <a href="{% url 'drivesafe:admin_home' %}" class="btn btn-primary mt-3" role="button">Back to Admin Home</a>
    </div>
    {% bootstrap_javascript %}
</body>
</html>
{% endblock %}

drivesafe/templates/drivesafe/form_submitted.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block content %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Report Submitted</title>
  {% bootstrap_css %}
</head>
<body>
  <div class="container">
    <div class="row justify-content-center mt-5">
      <div class="col-md-8 text-center">
        <div class="alert alert-success" role="alert">
          <h2 class="display-6">Your report has been successfully submitted!</h2>
        </div>
        <a href="{% url 'drivesafe:regular_user_home' %}" class="btn btn-primary btn-lg mt-3">Go to Dashboard</a>
      </div>
    </div>
  </div>

  {% bootstrap_javascript %}
</body>
</html>
{% endblock %}

drivesafe/templates/drivesafe/index.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% load socialaccount %}
{% block content %}
{% bootstrap_css %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Welcome to DriveSafe</title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>

</head>
<body>
  <div class="container">

    <div class="row">
      <div class = "shadow p-3 col-md-6 mt-5 bg-white rounded align-items-center justify-content-center">
        <img src="{% static 'road.jpg' %}"  class="img-fluid mx-auto" alt="uva image">
      </div>
      <div class="col-md-6 text-center mt-5">
        <span class="h1 fw-bold mb-0">Welcome to Drivesafe!</span>
        <p class="lead">Keep UVA safer by reporting rash driving.</p>

        <form action="{% url 'drivesafe:login' %}" method="post">
    {% csrf_token %}
    <div data-mdb-input-init class="form-floating mb-4">
        <input type="email" id="form1Example13" class="form-control form-control-lg" name="email">
        <label class="form-label" for="form1Example13">Email address</label>
    </div>

    <div data-mdb-input-init class="form-floating mb-4">
        <input type="password" id="form1Example23" class="form-control form-control-lg" name="password">
        <label class="form-label" for="form1Example23">Password</label>
    </div>

    <button type="submit" class="btn btn-primary">Sign in</button>
</form>
        <div class="divider d-flex align-items-center my-4">
            <p class="text-center fw-bold mx-3 mb-0 text-muted">OR</p>
          </div>

          <a data-mdb-ripple-init class="btn btn-lg btn-block btn-primary" style="background-color: #dd4b39;" href="{% provider_login_url 'google' %}"
            role="button">
            <i class="fab fa-google me-2"></i>Continue with Google
          </a>

        <a data-mdb-ripple-init class="btn btn-warning btn-lg btn-block"  href="{% url 'drivesafe:anonymous_report' %}"
            role="button">
            <i></i>Report Anonymously
          </a>
      </div>
    </div>
  </div>

  {% bootstrap_javascript %}
</body>

{% endblock %}

drivesafe/templates/drivesafe/regular_user_home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
</head>
<body>
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <h1><em>Welcome</em>, {{ username }}!</h1>
            {% if full_name %}
                <p>Full name: {{ full_name }}</p>
            {% endif %}
            <div class="card mt-3 shadow" style="background-color: rgba(255, 255, 255, 0.3);">
                <div class="card-body">
                    <h5 class="card-title">Current Date and Time</h5>
                    <p class="card-text" id="currentDateTime">{{ current_date_and_time }}</p>
                </div>
            </div>

            <a href="{% url 'drivesafe:report' %}" class="btn btn-primary mt-3" role="button">Report a Driver</a>
            <a href="{% url 'drivesafe:user_submissions' %}" class="btn btn-primary mt-3" role="button">View User Submissions</a>

            <form action="{% url 'account_logout' %}" method="post" class="mt-3">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Sign Out</button>
            </form>
        </div>
    </div>
</div>
{% bootstrap_javascript %}
<script>
    // Update current date and time every second
    setInterval(function() {
        var now = new Date();
        var dateTimeString = now.toLocaleString();
        document.getElementById('currentDateTime').innerText = dateTimeString;
    }, 1000);

    // Initial update of date and time
    var initialNow = new Date();
    var initialDateTimeString = initialNow.toLocaleString();
    document.getElementById('currentDateTime').innerText = initialDateTimeString;
</script>
</body>
</html>
{% endblock %}

drivesafe/templates/drivesafe/site_admin_home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
</head>
<body>
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <h1><em>Welcome</em>, {{ username }}!</h1>
            {% if full_name %}
                <p>Full name: {{ full_name }}</p>
            {% endif %}
            <div class="card mt-3 shadow" style="background-color: rgba(255, 255, 255, 0.3);">
                <div class="card-body">
                    <h5 class="card-title">Current Date and Time</h5>
                    <p class="card-text" id="currentDateTime">{{ current_date_and_time }}</p>
                </div>
            </div>

            <a href="{% url 'drivesafe:submissions' %}" class="btn btn-primary mt-3" role="button">View Submitted Reports</a>
            <a href="{% url 'drivesafe:common_words' %}" class="btn btn-primary mt-3" role="button">Frequent Words</a>

            <form action="{% url 'account_logout' %}" method="post" class="mt-3">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Sign Out</button>
            </form>
        </div>
    </div>
</div>
{% bootstrap_javascript %}
<script>
    setInterval(function() {
        var now = new Date();
        var dateTimeString = now.toLocaleString();
        document.getElementById('currentDateTime').innerText = dateTimeString;
    }, 1000);

    var initialNow = new Date();
    var initialDateTimeString = initialNow.toLocaleString();
    document.getElementById('currentDateTime').innerText = initialDateTimeString;
</script>
</body>
</html>
{% endblock %}

drivesafe/templates/drivesafe/view_user_submissions.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View User Submissions</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
</head>
<body>
    <div class="container mt-5">
        <h1>View Submissions</h1>
        <div class="row mt-3">
            {% for submission in user_submissions %}
            <div class="col-md-6">
                <div class="card mb-3">
                    {% if not submission.update_seen %}
                    <div class="card-header bg-warning text-dark">
                        New Update!
                    </div>
                    {% endif %}
                    <div class="card-body">
                        {% if submission.pdf_file %}
                        <p>PDF File: <a href="{{ submission.pdf_file.url }}">{{ submission.pdf_file }}</a></p>
                        {% else %}
                        <p>No PDF file uploaded.</p>
                        {% endif %}

                        {% if submission.jpg_file %}
                        <p>JPG File: <a href="{{ submission.jpg_file.url }}">{{ submission.jpg_file }}</a></p>
                        {% else %}
                        <p>No JPG file uploaded.</p>
                        {% endif %}

                        {% if submission.txt_file %}
                        <p>TXT File: <a href="{{ submission.txt_file.url }}">{{ submission.txt_file }}</a></p>
                        {% else %}
                        <p>No TXT file uploaded.</p>
                        {% endif %}

                        <p>Location: {{ submission.location }}</p>
                        <p>Car Color: {{ submission.car_color }}</p>
                        <p>Car Model: {{ submission.car_model }}</p>
                        <p>Car Identifying Features: {{ submission.car_identifying_features }}</p>
                        <p>Driver Details: {{ submission.driver_details }}</p>
                        <p>Additional Information: {{ submission.additional_information }}</p>
                        <div class="alert alert-primary d-inline-flex align-items-center mt-3" role="alert">
                            <i class="fas fa-info-circle"></i>
                            <div class="d-inline">
                                Status: {{ submission.status }}
                            </div>
                        </div>
                        <p>Admin Response: {{ submission.admin_response }}</p>
                        <form method="post" action="{% url 'drivesafe:delete_submission' submission.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete This Submission</button>
                        </form>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <p>No submissions found.</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% bootstrap_javascript %}
</body>
</html>
{% endblock %}